 opt_in_rules:
    - closure_end_indentation
    - closure_spacing
    - empty_count
    - explicit_init
    - fatal_error_message
    - first_where
    - operator_usage_whitespace
    - overridden_super_call
    - prohibited_super_call
    - redundant_nil_coalescing
    - multiline_parameters
    - vertical_parameter_alignment_on_call
    - joined_default_parameter
    - unneeded_parentheses_in_closure_argument
    - missing_docs

 disabled_rules:
    - unused_setter_value
    - file_length
    - valid_ibinspectable
    - shorthand_operator
    - file_header
    - discarded_notification_center_observer
    - empty_enum_arguments
    - prohibited_super_call
    - line_length  
    - type_name  

 excluded:
    - Carthage
    - Pods
    - Streaming_AmazingApp
 
 identifier_name:
    min_length: 1
    max_length:
      warning: 50
      error: 60

 function_body_length:
    warning: 70
    error: 120

 custom_rules:    
    no_direct_standard_out_logs:
      name: "Writing log messages directly to standar out is disallowed"
      regex: "(\\bprint|\\bdebugPrint|\\bdump|Swifit\\.print|Swifit\\.debugPrint|Swift\\.dump)\\s*\\("  
      match_kinds:
       - identifier
      message: "Don't commit `print(..)` `debugPrint(..)`, or  `dumb(..)` as they write to standard out in release. Either log to a dedicated loggin system"   
      severity: warning  
